name: demo_suraj
description: ''
version: 0.0.1
author: suraj.thakur@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demosuraj
  parentArtefactID: santoshcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-11 10:35:13'
pipelines:
  pipelines/PricingSummary:
    name: PricingSummary
    description: Report for prices, descounts and shopping status
    author: suraj.thakur@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-11 12:56:12'
    datasets:
      inputs:
      - datasets/dataset_suraj
      outputs:
      - datasets/target
    subgraphs: []
    dependencies: {}
datasets:
  datasets/first_dataset:
    name: first_dataset
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-11 10:43:35'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-11 10:43:35'
  datasets/dataset_suraj:
    name: dataset_suraj
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-11 13:08:57'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-11 13:08:57'
  datasets/target:
    name: target
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-11 13:22:28'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: Database
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-11 13:22:28'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-11 10:35:13'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-11 10:34:43'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-11 10:34:43'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
