name: project_demo_suraj2
description: ''
version: v0.9
author: suraj.thakur@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projectdemosuraj2
  parentArtefactID: surajthakurcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-13 13:32:05'
pipelines:
  pipelines/pipeline1:
    name: pipeline1
    description: ''
    author: suraj.thakur@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-13 13:32:05'
    datasets:
      inputs:
      - datasets/dataset1
      outputs:
      - datasets/dataset2
    subgraphs: []
    dependencies: {}
datasets:
  datasets/dataset1:
    name: dataset1
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-13 13:34:33'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-13 13:34:33'
  datasets/dataset2:
    name: dataset2
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-13 13:36:24'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-13 13:36:25'
templates: {}
jobs:
  jobs/schedule2:
    name: schedule2
    description: ''
    fabricUID: 10150
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: suraj.thakur@cloudaeon.net
      onStart: true
      onSuccess: true
      onFailure: false
    pipelines:
    - pipelines/pipeline1
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-03-13 14:00:36'
    author: suraj.thakur@cloudaeon.net
  jobs/scheduler_airflow:
    name: scheduler_airflow
    description: ''
    fabricUID: 10459
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/15 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pipeline1
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-03-20 07:47:09'
    author: suraj.thakur@cloudaeon.net
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-13 13:32:05'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-13 13:31:46'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-13 13:31:46'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
